name 'altt'
maintainer 'Kristian Holdich'
maintainer_email 'kristian@smkd.net'
license 'Apache 2.0'
description 'Installs/Configures altt'
long_description 'Installs/Configures altt'
version '0.1.0'

depends 'nginx', '2.7.6'
depends 'supervisor', '0.4.12'